/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  static EMPTY  = 'empty';
  static WIFI  = 'wifi';
  static SIGNAL = 'signal';
  static CLOCK = 'clock';
  static BATTERY = 'battery';
  static CAPSULE = 'capsule'
  static NOTIFICATION = 'notification';

  static STATIC_BAR_ICON_WIDTH = 24;
  static STATIC_BAR_ICON_MARGIN = 2;
  static STATIC_BAR_ICON_HEIGHT = 24;
  static STATIC_BAR_ICON_INSIDE_SPACE = 2;
  static STATIC_BAR_ICON_OUTSIDE_MARGIN = 5;

  static EMPTY_AREA_POSITION_LEFT = 'left';
  static EMPTY_AREA_POSITION_CENTER = 'center';
  static EMPTY_AREA_POSITION_RIGHT = 'right';

  static GROUP_ID_LEFT = 1;
  static GROUP_ID_CENTER = 2;
  static GROUP_ID_RIGHT = 3;
}